"""
Sample Mercari Japan product data for simulation
In production, this would be replaced with actual scraping from Mercari Japan
"""

SAMPLE_MERCARI_DATA = [
    {
        "id": "m001",
        "name": "iPhone 14 Pro Max 256GB スペースブラック",
        "price": 128000,
        "condition": "very_good",
        "seller_rating": 4.8,
        "category": "Electronics",
        "brand": "Apple",
        "image_url": "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m001",
        "description": "iPhone 14 Pro Max in excellent condition. Minor wear on corners."
    },
    {
        "id": "m002",
        "name": "Nintendo Switch 有機ELモデル ホワイト",
        "price": 35800,
        "condition": "like_new",
        "seller_rating": 4.9,
        "category": "Gaming",
        "brand": "Nintendo",
        "image_url": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m002",
        "description": "Nintendo Switch OLED model in pristine condition with original box."
    },
    {
        "id": "m003",
        "name": "MacBook Air M2 13インチ スターライト 8GB/256GB",
        "price": 145000,
        "condition": "good",
        "seller_rating": 4.7,
        "category": "Electronics",
        "brand": "Apple",
        "image_url": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m003",
        "description": "MacBook Air M2 in good working condition. Some scratches on lid."
    },
    {
        "id": "m004",
        "name": "ポケモンカード ピカチュウ プロモ PSA10",
        "price": 25000,
        "condition": "new",
        "seller_rating": 4.6,
        "category": "Trading Cards",
        "brand": "Pokemon",
        "image_url": "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m004",
        "description": "PSA 10 graded Pikachu promotional card in perfect condition."
    },
    {
        "id": "m005",
        "name": "AirPods Pro 第2世代 MQD83J/A",
        "price": 28000,
        "condition": "very_good",
        "seller_rating": 4.8,
        "category": "Electronics",
        "brand": "Apple",
        "image_url": "https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m005",
        "description": "AirPods Pro 2nd generation with original charging case and accessories."
    },
    {
        "id": "m006",
        "name": "ルイヴィトン モノグラム スピーディ30",
        "price": 85000,
        "condition": "good",
        "seller_rating": 4.5,
        "category": "Fashion",
        "brand": "Louis Vuitton",
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m006",
        "description": "Authentic Louis Vuitton Monogram Speedy 30 handbag."
    },
    {
        "id": "m007",
        "name": "PlayStation 5 本体 CFI-1200A01",
        "price": 68000,
        "condition": "very_good",
        "seller_rating": 4.9,
        "category": "Gaming",
        "brand": "Sony",
        "image_url": "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m007",
        "description": "PlayStation 5 console in excellent condition with all original accessories."
    },
    {
        "id": "m008",
        "name": "ロレックス サブマリーナ 116610LN",
        "price": 1250000,
        "condition": "very_good",
        "seller_rating": 4.7,
        "category": "Watches",
        "brand": "Rolex",
        "image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m008",
        "description": "Rolex Submariner Date with box and papers. Serviced recently."
    },
    {
        "id": "m009",
        "name": "iPad Pro 12.9インチ 第6世代 Wi-Fi 128GB スペースグレイ",
        "price": 125000,
        "condition": "like_new",
        "seller_rating": 4.8,
        "category": "Electronics",
        "brand": "Apple",
        "image_url": "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m009",
        "description": "iPad Pro 12.9-inch 6th generation in like-new condition with screen protector."
    },
    {
        "id": "m010",
        "name": "デュエルマスターズ ブラック・ロータス プロモ",
        "price": 45000,
        "condition": "good",
        "seller_rating": 4.6,
        "category": "Trading Cards",
        "brand": "Takara Tomy",
        "image_url": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m010",
        "description": "Duel Masters Black Lotus promotional card in good condition."
    },
    {
        "id": "m011",
        "name": "チャンピオン リバースウィーブ パーカー USA製 ビンテージ",
        "price": 15000,
        "condition": "good",
        "seller_rating": 4.4,
        "category": "Fashion",
        "brand": "Champion",
        "image_url": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m011",
        "description": "Vintage Champion Reverse Weave hoodie made in USA."
    },
    {
        "id": "m012",
        "name": "Canon EOS R6 Mark II ボディ",
        "price": 285000,
        "condition": "like_new",
        "seller_rating": 4.9,
        "category": "Electronics",
        "brand": "Canon",
        "image_url": "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m012",
        "description": "Canon EOS R6 Mark II camera body in excellent condition with low shutter count."
    },
    {
        "id": "m013",
        "name": "フェンディ バゲット バッグ ズッカ柄",
        "price": 120000,
        "condition": "good",
        "seller_rating": 4.6,
        "category": "Fashion",
        "brand": "Fendi",
        "image_url": "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m013",
        "description": "Authentic Fendi Baguette bag in Zucca canvas pattern."
    },
    {
        "id": "m014",
        "name": "ワンピース フィギュア ルフィ ギア5 POP",
        "price": 18000,
        "condition": "new",
        "seller_rating": 4.7,
        "category": "Collectibles",
        "brand": "Megahouse",
        "image_url": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m014",
        "description": "One Piece Luffy Gear 5 figure by Megahouse, brand new in box."
    },
    {
        "id": "m015",
        "name": "Supreme Box Logo パーカー グレー Lサイズ",
        "price": 55000,
        "condition": "very_good",
        "seller_rating": 4.5,
        "category": "Fashion",
        "brand": "Supreme",
        "image_url": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m015",
        "description": "Supreme Box Logo hoodie in grey, size L, authentic with tags."
    },
    {
        "id": "m016",
        "name": "CHANEL ココマーク イヤリング ゴールド",
        "price": 65000,
        "condition": "very_good",
        "seller_rating": 4.8,
        "category": "Fashion",
        "brand": "Chanel",
        "image_url": "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m016",
        "description": "Authentic Chanel Coco mark earrings in gold, excellent condition."
    },
    {
        "id": "m017",
        "name": "遊戯王 ブルーアイズホワイトドラゴン 初期",
        "price": 35000,
        "condition": "good",
        "seller_rating": 4.7,
        "category": "Trading Cards",
        "brand": "Konami",
        "image_url": "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m017",
        "description": "Yu-Gi-Oh Blue-Eyes White Dragon first edition card in good condition."
    },
    {
        "id": "m018",
        "name": "ドラゴンボール フィギュア 超サイヤ人悟空",
        "price": 12000,
        "condition": "new",
        "seller_rating": 4.9,
        "category": "Collectibles",
        "brand": "Bandai",
        "image_url": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m018",
        "description": "Dragon Ball Super Saiyan Goku figure by Bandai, brand new in box."
    },
    {
        "id": "m019",
        "name": "iPhone 15 Pro 128GB ナチュラルチタニウム",
        "price": 165000,
        "condition": "like_new",
        "seller_rating": 4.9,
        "category": "Electronics",
        "brand": "Apple",
        "image_url": "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m019",
        "description": "iPhone 15 Pro 128GB in Natural Titanium, like new condition with box."
    },
    {
        "id": "m020",
        "name": "Nike Air Jordan 1 Retro High OG シカゴ",
        "price": 48000,
        "condition": "very_good",
        "seller_rating": 4.6,
        "category": "Fashion",
        "brand": "Nike",
        "image_url": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m020",
        "description": "Nike Air Jordan 1 Retro High OG Chicago colorway in very good condition."
    },
    {
        "id": "m021",
        "name": "Sony WH-1000XM5 ワイヤレスヘッドホン",
        "price": 32000,
        "condition": "like_new",
        "seller_rating": 4.8,
        "category": "Electronics",
        "brand": "Sony",
        "image_url": "https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m021",
        "description": "Sony WH-1000XM5 wireless noise-canceling headphones, like new."
    },
    {
        "id": "m022",
        "name": "任天堂 ゲームボーイ ポケットモンスター 赤",
        "price": 8500,
        "condition": "good",
        "seller_rating": 4.5,
        "category": "Gaming",
        "brand": "Nintendo",
        "image_url": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m022",
        "description": "Nintendo Game Boy Pokémon Red version in good working condition."
    },
    {
        "id": "m023",
        "name": "グッチ GGマーモント レザーベルト",
        "price": 42000,
        "condition": "very_good",
        "seller_rating": 4.7,
        "category": "Fashion",
        "brand": "Gucci",
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m023",
        "description": "Authentic Gucci GG Marmont leather belt in very good condition."
    },
    {
        "id": "m024",
        "name": "ダイソン V15 Detect コードレス掃除機",
        "price": 68000,
        "condition": "like_new",
        "seller_rating": 4.9,
        "category": "Home & Kitchen",
        "brand": "Dyson",
        "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m024",
        "description": "Dyson V15 Detect cordless vacuum cleaner in like new condition."
    },
    # Additional Electronics
    {
        "id": "m025",
        "name": "Samsung Galaxy S24 Ultra 256GB チタン",
        "price": 185000,
        "condition": "like_new",
        "seller_rating": 4.9,
        "category": "Electronics",
        "brand": "Samsung",
        "image_url": "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m025",
        "description": "Samsung Galaxy S24 Ultra in Titanium color, like new with box and accessories."
    },
    {
        "id": "m026",
        "name": "MacBook Pro 14インチ M3 Pro 512GB スペースブラック",
        "price": 285000,
        "condition": "very_good",
        "seller_rating": 4.8,
        "category": "Electronics",
        "brand": "Apple",
        "image_url": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m026",
        "description": "MacBook Pro 14-inch M3 Pro in excellent condition with AppleCare+."
    },
    {
        "id": "m027",
        "name": "iPad Air 第5世代 64GB ブルー",
        "price": 85000,
        "condition": "good",
        "seller_rating": 4.6,
        "category": "Electronics",
        "brand": "Apple",
        "image_url": "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m027",
        "description": "iPad Air 5th generation in blue, good condition with minor scratches."
    },
    {
        "id": "m028",
        "name": "Google Pixel 8 Pro 256GB オブシディアン",
        "price": 125000,
        "condition": "like_new",
        "seller_rating": 4.7,
        "category": "Electronics",
        "brand": "Google",
        "image_url": "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m028",
        "description": "Google Pixel 8 Pro in Obsidian color, like new with original box."
    },
    {
        "id": "m029",
        "name": "Fujifilm X-T5 ボディ ブラック",
        "price": 185000,
        "condition": "very_good",
        "seller_rating": 4.8,
        "category": "Electronics",
        "brand": "Fujifilm",
        "image_url": "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m029",
        "description": "Fujifilm X-T5 camera body in excellent condition with low shutter count."
    },
    {
        "id": "m030",
        "name": "Bose QuietComfort Ultra ヘッドホン",
        "price": 45000,
        "condition": "like_new",
        "seller_rating": 4.9,
        "category": "Electronics",
        "brand": "Bose",
        "image_url": "https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m030",
        "description": "Bose QuietComfort Ultra headphones, like new with carrying case."
    },
    # Additional Gaming
    {
        "id": "m031",
        "name": "Xbox Series X 本体",
        "price": 58000,
        "condition": "very_good",
        "seller_rating": 4.8,
        "category": "Gaming",
        "brand": "Microsoft",
        "image_url": "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m031",
        "description": "Xbox Series X console in excellent condition with controller."
    },
    {
        "id": "m032",
        "name": "Nintendo Switch Lite イエロー",
        "price": 22000,
        "condition": "good",
        "seller_rating": 4.5,
        "category": "Gaming",
        "brand": "Nintendo",
        "image_url": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m032",
        "description": "Nintendo Switch Lite in yellow, good condition with screen protector."
    },
    {
        "id": "m033",
        "name": "PlayStation 4 Pro 1TB ジェットブラック",
        "price": 35000,
        "condition": "good",
        "seller_rating": 4.6,
        "category": "Gaming",
        "brand": "Sony",
        "image_url": "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m033",
        "description": "PlayStation 4 Pro 1TB in good working condition with controller."
    },
    {
        "id": "m034",
        "name": "Steam Deck 256GB",
        "price": 65000,
        "condition": "like_new",
        "seller_rating": 4.9,
        "category": "Gaming",
        "brand": "Valve",
        "image_url": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m034",
        "description": "Steam Deck 256GB in like new condition with carrying case."
    },
    {
        "id": "m035",
        "name": "Nintendo 3DS LL メタリックブラック",
        "price": 18000,
        "condition": "good",
        "seller_rating": 4.4,
        "category": "Gaming",
        "brand": "Nintendo",
        "image_url": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m035",
        "description": "Nintendo 3DS LL in metallic black, good condition with stylus."
    },
    # Additional Fashion
    {
        "id": "m036",
        "name": "エルメス ビルキン 30cm トゴレザー ゴールド",
        "price": 2800000,
        "condition": "very_good",
        "seller_rating": 4.9,
        "category": "Fashion",
        "brand": "Hermes",
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m036",
        "description": "Authentic Hermes Birkin 30cm in Togo leather, gold hardware."
    },
    {
        "id": "m037",
        "name": "バレンシアガ シティバッグ ミニ ブラック",
        "price": 180000,
        "condition": "good",
        "seller_rating": 4.6,
        "category": "Fashion",
        "brand": "Balenciaga",
        "image_url": "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m037",
        "description": "Balenciaga City Bag Mini in black leather, good condition."
    },
    {
        "id": "m038",
        "name": "アディダス YEEZY BOOST 350 V2 ゼブラ",
        "price": 85000,
        "condition": "very_good",
        "seller_rating": 4.7,
        "category": "Fashion",
        "brand": "Adidas",
        "image_url": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m038",
        "description": "Adidas Yeezy Boost 350 V2 Zebra in very good condition, size US 9."
    },
    {
        "id": "m039",
        "name": "コーチ タバサ バッグ シグネチャー",
        "price": 45000,
        "condition": "good",
        "seller_rating": 4.5,
        "category": "Fashion",
        "brand": "Coach",
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m039",
        "description": "Coach Tabby bag in signature canvas, good condition."
    },
    {
        "id": "m040",
        "name": "プーマ RS-X レトロ ホワイト",
        "price": 12000,
        "condition": "very_good",
        "seller_rating": 4.6,
        "category": "Fashion",
        "brand": "Puma",
        "image_url": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m040",
        "description": "Puma RS-X Retro in white, very good condition, size US 8."
    },
    # Additional Trading Cards
    {
        "id": "m041",
        "name": "マジック・ザ・ギャザリング ブラック・ロータス アンリミテッド",
        "price": 850000,
        "condition": "good",
        "seller_rating": 4.8,
        "category": "Trading Cards",
        "brand": "Wizards of the Coast",
        "image_url": "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m041",
        "description": "Magic: The Gathering Black Lotus Unlimited Edition in good condition."
    },
    {
        "id": "m042",
        "name": "ポケモンカード シャイニング・チャリザード 1st Edition",
        "price": 450000,
        "condition": "very_good",
        "seller_rating": 4.9,
        "category": "Trading Cards",
        "brand": "Pokemon",
        "image_url": "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m042",
        "description": "Pokemon Shining Charizard 1st Edition in very good condition."
    },
    {
        "id": "m043",
        "name": "遊戯王 エクゾディア 完全体 初期",
        "price": 28000,
        "condition": "good",
        "seller_rating": 4.7,
        "category": "Trading Cards",
        "brand": "Konami",
        "image_url": "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m043",
        "description": "Yu-Gi-Oh Exodia the Forbidden One complete set in good condition."
    },
    {
        "id": "m044",
        "name": "デュエルマスターズ ボルメテウス・ファイアー・ドラゴン",
        "price": 15000,
        "condition": "very_good",
        "seller_rating": 4.6,
        "category": "Trading Cards",
        "brand": "Takara Tomy",
        "image_url": "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m044",
        "description": "Duel Masters Bolmeteus Fire Dragon in very good condition."
    },
    {
        "id": "m045",
        "name": "デジモンカード オメガモン プロモ",
        "price": 8500,
        "condition": "good",
        "seller_rating": 4.5,
        "category": "Trading Cards",
        "brand": "Bandai",
        "image_url": "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m045",
        "description": "Digimon Card Omegamon promotional card in good condition."
    },
    # Additional Collectibles
    {
        "id": "m046",
        "name": "ナルト フィギュア うずまきナルト 仙人モード",
        "price": 22000,
        "condition": "new",
        "seller_rating": 4.8,
        "category": "Collectibles",
        "brand": "Megahouse",
        "image_url": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m046",
        "description": "Naruto Uzumaki Sage Mode figure by Megahouse, brand new in box."
    },
    {
        "id": "m047",
        "name": "鬼滅の刃 フィギュア 竈門炭治郎 全集中",
        "price": 18000,
        "condition": "new",
        "seller_rating": 4.7,
        "category": "Collectibles",
        "brand": "Aniplex",
        "image_url": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m047",
        "description": "Demon Slayer Tanjiro Kamado Total Concentration figure, brand new."
    },
    {
        "id": "m048",
        "name": "進撃の巨人 フィギュア リヴァイ兵長",
        "price": 25000,
        "condition": "like_new",
        "seller_rating": 4.9,
        "category": "Collectibles",
        "brand": "Good Smile Company",
        "image_url": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m048",
        "description": "Attack on Titan Levi Ackerman figure by Good Smile Company."
    },
    {
        "id": "m049",
        "name": "スパイダーマン フィギュア マイルス・モラレス",
        "price": 15000,
        "condition": "new",
        "seller_rating": 4.6,
        "category": "Collectibles",
        "brand": "Hot Toys",
        "image_url": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m049",
        "description": "Spider-Man Miles Morales figure by Hot Toys, brand new in box."
    },
    {
        "id": "m050",
        "name": "スター・ウォーズ フィギュア ダース・ベイダー",
        "price": 28000,
        "condition": "very_good",
        "seller_rating": 4.8,
        "category": "Collectibles",
        "brand": "Sideshow Collectibles",
        "image_url": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m050",
        "description": "Star Wars Darth Vader figure by Sideshow Collectibles."
    },
    # Additional Watches
    {
        "id": "m051",
        "name": "オメガ スピードマスター プロフェッショナル",
        "price": 850000,
        "condition": "very_good",
        "seller_rating": 4.9,
        "category": "Watches",
        "brand": "Omega",
        "image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m051",
        "description": "Omega Speedmaster Professional with box and papers."
    },
    {
        "id": "m052",
        "name": "カシオ G-SHOCK DW-5600E-1V",
        "price": 8500,
        "condition": "good",
        "seller_rating": 4.5,
        "category": "Watches",
        "brand": "Casio",
        "image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m052",
        "description": "Casio G-Shock DW-5600E-1V in good condition."
    },
    {
        "id": "m053",
        "name": "セイコー プレザージュ SARB035",
        "price": 45000,
        "condition": "very_good",
        "seller_rating": 4.7,
        "category": "Watches",
        "brand": "Seiko",
        "image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m053",
        "description": "Seiko Presage SARB035 in very good condition with original strap."
    },
    {
        "id": "m054",
        "name": "タグ・ホイヤー カレラ クロノグラフ",
        "price": 280000,
        "condition": "good",
        "seller_rating": 4.6,
        "category": "Watches",
        "brand": "Tag Heuer",
        "image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m054",
        "description": "Tag Heuer Carrera chronograph in good condition."
    },
    {
        "id": "m055",
        "name": "シチズン エコ・ドライブ プロマスター",
        "price": 18000,
        "condition": "very_good",
        "seller_rating": 4.4,
        "category": "Watches",
        "brand": "Citizen",
        "image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m055",
        "description": "Citizen Eco-Drive Promaster in very good condition."
    },
    # Additional Home & Kitchen
    {
        "id": "m056",
        "name": "象印 圧力IH炊飯ジャー NP-VD10",
        "price": 45000,
        "condition": "like_new",
        "seller_rating": 4.8,
        "category": "Home & Kitchen",
        "brand": "Zojirushi",
        "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m056",
        "description": "Zojirushi Pressure IH Rice Cooker NP-VD10 in like new condition."
    },
    {
        "id": "m057",
        "name": "パナソニック ナノケア ドライヤー EH-NA99",
        "price": 28000,
        "condition": "very_good",
        "seller_rating": 4.7,
        "category": "Home & Kitchen",
        "brand": "Panasonic",
        "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m057",
        "description": "Panasonic Nanoe Hair Dryer EH-NA99 in very good condition."
    },
    {
        "id": "m058",
        "name": "シャープ プラズマクラスター 空気清浄機 KC-G50",
        "price": 35000,
        "condition": "good",
        "seller_rating": 4.6,
        "category": "Home & Kitchen",
        "brand": "Sharp",
        "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m058",
        "description": "Sharp Plasmacluster Air Purifier KC-G50 in good condition."
    },
    {
        "id": "m059",
        "name": "三菱 霧ヶ峰 エアコン MSZ-ZW5622S",
        "price": 85000,
        "condition": "like_new",
        "seller_rating": 4.9,
        "category": "Home & Kitchen",
        "brand": "Mitsubishi",
        "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m059",
        "description": "Mitsubishi Kirigamine Air Conditioner MSZ-ZW5622S in like new condition."
    },
    {
        "id": "m060",
        "name": "日立 ビートウォッシュ 洗濯機 BD-V9800",
        "price": 125000,
        "condition": "very_good",
        "seller_rating": 4.8,
        "category": "Home & Kitchen",
        "brand": "Hitachi",
        "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m060",
        "description": "Hitachi Beat Wash Washing Machine BD-V9800 in very good condition."
    },
    # Additional Fashion Items
    {
        "id": "m061",
        "name": "プルダ レザージャケット ブラック",
        "price": 85000,
        "condition": "good",
        "seller_rating": 4.6,
        "category": "Fashion",
        "brand": "Prada",
        "image_url": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=150&h=150&fit=crop&crop=center",
        "url": "https://jp.mercari.com/item/m061",
        "description": "Prada leather jacket in black, good condition, size M."
    },
]